server:
  port: 8090

# Set here configurations for the database connection
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springsecurity
    username: root
    password: d1p10m4d0j4v4
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/SpringBootAppTest/protocol/openid-connect/certs

# LOGGING LEVEL
logging:
  level:
    root: INFO

# JWT
jwt:
  secret: 5f39c83d2d0482e07b5306f3f5a0fd8e1b4e9844987121ba4b99f3f4805fd4f85cc0f24ece8556dd10456a45d20cd2d61e7c36a77583674be979b071b869f34f
  expirationDateInMs: 3600
  refreshExpirationDateInMs: 900
