# ===============================
# = GLOBAL CONFIG
# ===============================
spring.application.name=${SPRING_APP_NAME:DIP_SPRING_SECURITY}
server.port=${SERVER_PORT:8090}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}
logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

# aca va localhost en su caso
ldap.url=${LDAP_URL:ldap://172.16.91.130:10389}
ldap.base=${LDAP_BASE:dc=unam,dc=org}
ldap.manager-dn=${LDAP_DN:uid=admin,ou=system}
ldap.manager-password=${LDAP_PASS:secret}
